package automate.utils.common;

public class Locaters {
	public static String userName="//input[@name=\"username\"]";
	public static String password="//input[@id=\"passwordtxt\"]";
	public static String loginBtn="//span[text()=\" Login \"]/..";
	public static String logo="//img[@class=\"app-logo-text ng-star-inserted\"]";
	public static String hidingButton="//button[@id=\"hidingButton\"]";
	public static String dynamicidlink="//a[text()=\"Dynamic ID\"]";
	public static String classAttributeLink="//a[text()=\"Class Attribute\"]";
	public static String hiddenLayersLink="//a[text()=\"Hidden Layers\"]";
	public static String loadDelayLink="//a[text()=\"Load Delay\"]";
	public static String ajaxDataLink="//a[text()=\"AJAX Data\"]";
	public static String clientSideDelayLink="//a[text()=\"Client Side Delay\"]";
	public static String clickLink="//a[text()=\"Click\"]";
	public static String textInputLink="//a[text()=\"Text Input\"]";
	public static String scrollbarsLink="//a[text()=\"Scrollbars\"]";
	public static String dynamicTableLink="//a[text()=\"Dynamic Table\"]";
	public static String verifytextLink="//a[text()=\"Verify Text\"]";
	public static String progressBarLink="//a[text()=\"Progress Bar\"]";
	public static String visibilityLink = "//a[text()=\"Visibility\"]";
	public static String sampleAppLink = "//a[text()=\"Sample App\"]";
	public static String mousehoverLink="//a[text()=\"Mouse Over\"]";
	public static String nonBreakingSpaceLink="//a[text()=\"Non-Breaking Space\"]";
	public static String overlappedElementLink="//a[text()=\"Overlapped Element\"]";
	public static String shadowDomLink="//a[text()=\"Shadow DOM\"]";
	public static String buttonWithdynamicId="//button[text()=\"Button with Dynamic ID\"]";
	public static String btnPrimary="//button[contains(@class,'btn-primary')]";
	public static String btnSuccess="//button[contains(@class,'btn-success ')]";
	public static String btnWarning="//button[contains(@class,'btn-warning')]";
	public static String greenButton="//button[@id=\"greenButton\"]";
	public static String buttonAppearingaterDelay="//button[text()=\"Button Appearing After Delay\"]";
	public static String buttonTriggeringAJAXRequest="//button[text()=\"Button Triggering AJAX Request\"]";
	public static String dataloadedwithAJAXGetrequest="//p[text()=\"Data loaded with AJAX get request.\"]";
	public static String buttonTriggeringClientSideLogic="//button[text()=\"Button Triggering Client Side Logic\"]";
	public static String dataCalculatedOnTheClientSide="//p[text()=\"Data calculated on the client side.\"]";
	public static String buttonThatIgnoresDOMClickEvent="//button[text()=\"Button That Ignores DOM Click Event\"]";
	public static String buttonThatIgnoresDOMClickEventsuccuess="//button[@class=\"btn btn-success\"]";
	public static String textInput="//input[@id=\"newButtonName\"]";
	public static String updatingButton="//button[@id=\"updatingButton\"]";
	public static String chromeCPU="//span[text()=\"Chrome\"]/..//span[last()]";
	public static String actualChromeCPU="//p[text()=\"Chrome CPU: 4.3%\"]";
	public static String verifyText="//span[normalize-space(.)='Welcome UserName!' and @class=\"badge-secondary\"]";
	public static String startButton="//button[@id=\"startButton\"]";
	public static String stopButton="//button[@id=\"stopButton\"]";
	public static String progressBar="//div[@id=\"progressBar\"]";
	public static String hideButton="//button[@id=\"hideButton\"]";
	public static String removedButton="//button[@id=\"removedButton\"]";
	public static String zeroWidthButton="//button[@id=\"zeroWidthButton\"]";
	public static String overlappedButton="//button[@id=\"overlappedButton\"]";
	public static String transparentButton="//button[@id=\"transparentButton\"]";
	public static String invisibleButton="//button[@id=\"invisibleButton\"]";
	public static String notdisplayedButton="//button[@id=\"notdisplayedButton\"]";
	public static String offscreenButton="//button[@id=\"offscreenButton\"]";
	public static String userNameui="//input[@name=\"UserName\"]";
	public static String passwordui="//input[@name=\"Password\"]";
	public static String logIN="//button[@id=\"login\"]";
	public static String loginStatus="//label[text()=\"Invalid username/password\"]";
	public static String clickMe="//a[@title=\"Click me\"]";
	public static String linkedClickedTimes="//span[@id=\"clickCount\"]";
	public static String myButton="//button[contains(., 'My') and contains(., 'Button')]";
	public static String inputId="//input[@id=\"id\"]";
	public static String inputName="//input[@id=\"name\"]";
	public static String editfield="//input[@id=\"editField\"]";
	public static String buttonGenerate="//button[@id=\"buttonGenerate\"]";
	public static String buttonCopy="//button[@id=\"buttonCopy\"]";
	
	public static String orangeHRMLoginPageLogo="//img[@alt='company-branding']";
	public static String orangeHRNUserName="//input[@placeholder='Username']";
	public static String orangeHRMPassword="//input[@placeholder='Password']";
	public static String orangeHRMLoginButton="//button[@type='submit']";
	public static String orangeHRMDashboard="//h6[@class='oxd-text oxd-text--h6 oxd-topbar-header-breadcrumb-module']";
	public static String orangeHRMAdmin="//span[normalize-space()='Admin']/..";
	public static String orangeHRMAddUser="//i[@class='oxd-icon bi-plus oxd-button-icon']";
	
	public static String orangeHRMUserRole="//div[@class='oxd-select-text-input'][normalize-space()='-- Select --']/..";
	public static String oraneHRMSelectUser="(//div[contains(@class,\"select-dropdown\")]//div)[2]";
	public static String orangeHRMEmployeeName="//input[@placeholder='Type for hints...']";
	public static String  orangeHRMSelectEmployeeName="(//div[contains(@class,\"select-dropdown\")]//div)[2]";
	public static String orangeHRMStatus="//div[contains(text(),'-- Select --')]";
	public static String oraneHRMSelectStatus="(//div[contains(@class,\"select-dropdown\")]//div)[2]";
	public static String orangeHRMUsername="//label[text()=\"Username\"]/../..//input";
	public static String orangeHRMUserNewPassword="//label[text()=\"Password\"]/../..//input";
	public static String orangeHRMUserConfirmNewPassword="//label[text()=\"Confirm Password\"]/../..//input";
	public static String orangeHRMSaveUser="//button[@type='submit']";
	
	
}
